import {
  HOMEPAGE_SETTINGS_LIST_ITEM_ID,
  HOMEPAGE_SETTINGS_MIDDLE_PANE_ID,
  TESTIMONIAL_PENDING_EDIT_LIST_ITEM_ID,
  TESTIMONIAL_PUBLISHED_EDIT_LIST_ITEM_ID,
  TESTIMONIAL_DISCARDED_EDIT_LIST_ITEM_ID,
  TESTIMONIAL_SUBMISSIONS_LIST_ITEM_ID,
  TESTIMONIAL_SUBMISSIONS_MIDDLE_PANE_ID,
  TESTIMONIALS_DISCARDED_LIST_ID,
  TESTIMONIALS_DISCARDED_MIDDLE_PANE_ID,
  TESTIMONIALS_LIST_ITEM_ID,
  TESTIMONIALS_PUBLISHED_LIST_ID,
  TESTIMONIALS_PUBLISHED_MIDDLE_PANE_ID,
  TESTIMONIALS_SUBLIST_ID,
} from "../structurePaneIds";

const STRUCTURE_PANE_IDS = new Set([
  HOMEPAGE_SETTINGS_LIST_ITEM_ID,
  HOMEPAGE_SETTINGS_MIDDLE_PANE_ID,
  TESTIMONIALS_LIST_ITEM_ID,
  TESTIMONIALS_SUBLIST_ID,
  TESTIMONIAL_SUBMISSIONS_LIST_ITEM_ID,
  TESTIMONIAL_SUBMISSIONS_MIDDLE_PANE_ID,
  TESTIMONIAL_PENDING_EDIT_LIST_ITEM_ID,
  `${TESTIMONIAL_PENDING_EDIT_LIST_ITEM_ID}Pane`,
  TESTIMONIALS_PUBLISHED_LIST_ID,
  TESTIMONIALS_PUBLISHED_MIDDLE_PANE_ID,
  TESTIMONIAL_PUBLISHED_EDIT_LIST_ITEM_ID,
  `${TESTIMONIAL_PUBLISHED_EDIT_LIST_ITEM_ID}Pane`,
  `${TESTIMONIALS_PUBLISHED_LIST_ID}Documents`,
  TESTIMONIALS_DISCARDED_LIST_ID,
  TESTIMONIALS_DISCARDED_MIDDLE_PANE_ID,
  TESTIMONIAL_DISCARDED_EDIT_LIST_ITEM_ID,
  `${TESTIMONIAL_DISCARDED_EDIT_LIST_ITEM_ID}Pane`,
  `${TESTIMONIALS_DISCARDED_LIST_ID}Documents`,
]);

/** Document-type list panes from `S.documentTypeListItems()` use the schema name as pane id. */
const DOCUMENT_TYPE_LIST_PANE_IDS = new Set(["project"]);

export function isDocumentTypeListPaneId(id: string): boolean {
  const baseId = id.split(",")[0] ?? id;
  return DOCUMENT_TYPE_LIST_PANE_IDS.has(baseId);
}

export function isStructurePaneId(id: string): boolean {
  return STRUCTURE_PANE_IDS.has(id);
}
